#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

BEGIN = "# BEGIN CORTETSU HYPRLAND IMPORT"
END = "# END CORTETSU HYPRLAND IMPORT"
MAX_BYTES = 1024 * 1024
SKIP_DIRS = {".git", "backup", "backups", "cache", "logs", "legacy-backup"}
SKIP_SUFFIXES = (".bak", ".old", ".orig", ".tmp", ".swp", ".swo", "~")
SENSITIVE = re.compile(
    r"(?i)\b(password|passwd|api[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret)\b\s*[:=]"
)


class ImportError(RuntimeError):
    pass


@dataclass(frozen=True)
class Candidate:
    source: Path
    relative: Path
    size: int


def repo_root(value: str | None) -> Path:
    if value:
        return Path(value).expanduser().resolve()
    return Path(__file__).resolve().parents[1]


def active_root(home: Path) -> Path:
    return home / ".config/hypr/hyprland"


def imported_root(repo: Path) -> Path:
    return repo / "dotfiles/home/.config/hypr/hyprland"


def manifest_path(repo: Path) -> Path:
    return repo / "dotfiles/manifest.toml"


def is_backupish(path: Path) -> bool:
    lowered = path.name.lower()
    if any(part.lower() in SKIP_DIRS or part.lower().startswith("legacy-backup") for part in path.parts):
        return True
    return lowered.endswith(SKIP_SUFFIXES) or ".backup" in lowered


def inspect_file(path: Path) -> tuple[str, int]:
    try:
        size = path.stat().st_size
    except OSError as exc:
        return f"unreadable:{exc}", 0
    if size > MAX_BYTES:
        return "too-large", size
    try:
        raw = path.read_bytes()
    except OSError as exc:
        return f"unreadable:{exc}", size
    if b"\0" in raw:
        return "binary", size
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return "non-utf8", size
    if SENSITIVE.search(text):
        return "sensitive", size
    return "ok", size


def scan(home: Path) -> tuple[list[Candidate], list[tuple[Path, str]]]:
    root = active_root(home)
    if not root.is_dir():
        raise ImportError(f"árbol Hyprland activo inexistente: {root}")
    accepted: list[Candidate] = []
    rejected: list[tuple[Path, str]] = []
    for path in sorted(root.rglob("*"), key=lambda item: item.as_posix()):
        rel = path.relative_to(root)
        if is_backupish(rel):
            if path.is_file() or path.is_symlink():
                rejected.append((rel, "backup/temp"))
            continue
        if path.is_dir():
            continue
        if path.is_symlink():
            rejected.append((rel, "symlink"))
            continue
        if not path.is_file():
            rejected.append((rel, "non-regular"))
            continue
        reason, size = inspect_file(path)
        if reason == "ok":
            accepted.append(Candidate(path, rel, size))
        else:
            rejected.append((rel, reason))
    if not accepted:
        raise ImportError(f"no se encontraron archivos de configuración importables en {root}")
    return accepted, rejected


def render_entries(candidates: list[Candidate]) -> str:
    lines = [BEGIN, "# Generated by core/import_hyprland.py. Do not edit this block by hand."]
    for candidate in candidates:
        rel = candidate.relative.as_posix()
        source = f"dotfiles/home/.config/hypr/hyprland/{rel}"
        target = f".config/hypr/hyprland/{rel}"
        lines.extend(
            [
                "",
                "[[entry]]",
                f"source = {json.dumps(source)}",
                f"target = {json.dumps(target)}",
                'tags = ["hyprland"]',
            ]
        )
    lines.extend([END, ""])
    return "\n".join(lines)


def replace_generated_block(text: str, block: str) -> str:
    if BEGIN in text or END in text:
        if text.count(BEGIN) != 1 or text.count(END) != 1:
            raise ImportError("manifest contiene marcadores Hyprland inconsistentes")
        start = text.index(BEGIN)
        finish = text.index(END, start) + len(END)
        prefix = text[:start].rstrip()
        suffix = text[finish:].lstrip("\n")
        return f"{prefix}\n\n{block}{suffix}"
    return f"{text.rstrip()}\n\n{block}"


def check_repo_paths_clean(repo: Path) -> None:
    paths = ["dotfiles/manifest.toml", "dotfiles/home/.config/hypr/hyprland"]
    proc = subprocess.run(
        ["git", "-C", str(repo), "status", "--porcelain", "--", *paths],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if proc.returncode != 0:
        raise ImportError(proc.stderr.strip() or "no se pudo consultar git status")
    dirty = proc.stdout.strip()
    if dirty:
        raise ImportError("el área de importación Hyprland ya tiene cambios locales:\n" + dirty)


def validate_manifest(path: Path) -> None:
    with path.open("rb") as handle:
        payload = tomllib.load(handle)
    if payload.get("schema") != 1:
        raise ImportError("manifest resultante tiene schema inválido")
    targets: set[str] = set()
    for entry in payload.get("entry", []):
        target = str(entry.get("target", ""))
        if not target:
            raise ImportError("manifest resultante contiene target vacío")
        if target in targets:
            raise ImportError(f"target duplicado tras importación: {target}")
        targets.add(target)


def print_plan(home: Path, candidates: list[Candidate], rejected: list[tuple[Path, str]]) -> None:
    print(f"Cortetsu Hyprland import · source={active_root(home)}")
    for item in candidates:
        print(f"  import       {item.relative.as_posix()} ({item.size} B)")
    for rel, reason in rejected:
        mark = "BLOCKED" if reason == "sensitive" else "skip"
        print(f"  {mark:12} {rel.as_posix()} [{reason}]")
    print(f"SUMMARY import={len(candidates)} skipped={len(rejected)}")


def apply(repo: Path, home: Path, candidates: list[Candidate], rejected: list[tuple[Path, str]], commit: bool) -> int:
    sensitive = [rel for rel, reason in rejected if reason == "sensitive"]
    if sensitive:
        joined = ", ".join(path.as_posix() for path in sensitive)
        raise ImportError(f"importación bloqueada por posibles secretos: {joined}")
    check_repo_paths_clean(repo)
    manifest = manifest_path(repo)
    if not manifest.is_file():
        raise ImportError(f"manifest inexistente: {manifest}")
    original_manifest = manifest.read_text(encoding="utf-8")
    block = render_entries(candidates)
    updated_manifest = replace_generated_block(original_manifest, block)

    destination = imported_root(repo)
    destination.parent.mkdir(parents=True, exist_ok=True)
    backup = destination.with_name(f"{destination.name}.previous.{os.getpid()}")
    if backup.exists():
        shutil.rmtree(backup)

    with tempfile.TemporaryDirectory(prefix="cortetsu-hypr-import-", dir=destination.parent) as tmp:
        staging = Path(tmp) / "hyprland"
        staging.mkdir(parents=True)
        for candidate in candidates:
            out = staging / candidate.relative
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(candidate.source, out)

        manifest_tmp = manifest.with_name(f"{manifest.name}.tmp.{os.getpid()}")
        manifest_tmp.write_text(updated_manifest, encoding="utf-8")
        validate_manifest(manifest_tmp)
        try:
            if destination.exists():
                destination.rename(backup)
            staging.rename(destination)
            os.replace(manifest_tmp, manifest)
        except Exception:
            manifest_tmp.unlink(missing_ok=True)
            manifest.write_text(original_manifest, encoding="utf-8")
            if destination.exists():
                shutil.rmtree(destination)
            if backup.exists():
                backup.rename(destination)
            raise
        else:
            shutil.rmtree(backup, ignore_errors=True)

    print(f"IMPORTED hyprland={destination}")
    print(f"MANIFEST entries={len(candidates)}")
    if rejected:
        print(f"SKIPPED count={len(rejected)}")

    if commit:
        subprocess.run(
            ["git", "-C", str(repo), "add", "--", "dotfiles/manifest.toml", "dotfiles/home/.config/hypr/hyprland"],
            check=True,
        )
        diff = subprocess.run(["git", "-C", str(repo), "diff", "--cached", "--quiet"]).returncode
        if diff == 0:
            print("COMMIT skipped=no changes")
        else:
            host = socket.gethostname().split(".")[0]
            stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            subprocess.run(
                ["git", "-C", str(repo), "commit", "-m", f"feat(hyprland): import active config from {host} ({stamp})"],
                check=True,
            )
            print("COMMIT created=Hyprland import")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Safely import the active Hyprland tree into Cortetsu dotfiles")
    parser.add_argument("action", choices=("plan", "apply"), nargs="?", default="plan")
    parser.add_argument("--repo")
    parser.add_argument("--home", type=Path, default=Path.home())
    parser.add_argument("--commit", action="store_true", help="stage only imported Hyprland files and create a local commit")
    args = parser.parse_args()
    repo = repo_root(args.repo)
    home = args.home.expanduser().resolve()
    try:
        candidates, rejected = scan(home)
        print_plan(home, candidates, rejected)
        if args.action == "apply":
            return apply(repo, home, candidates, rejected, args.commit)
        return 2 if any(reason == "sensitive" for _, reason in rejected) else 0
    except (ImportError, OSError, subprocess.CalledProcessError, tomllib.TOMLDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
