#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import socket
import subprocess
import tempfile
import tomllib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

BEGIN = "# BEGIN CORTETSU FISH IMPORT"
END = "# END CORTETSU FISH IMPORT"
MAX_BYTES = 2 * 1024 * 1024
SKIP_DIRS = {".git", "backup", "backups", "cache", "logs", "tmp", "temp"}
SKIP_NAMES = {"fish_variables"}
SKIP_SUFFIXES = (".bak", ".old", ".orig", ".tmp", ".swp", ".swo", ".lock", ".log", "~")
SENSITIVE = re.compile(
    r"(?i)\b(password|passwd|api[_-]?key|access[_-]?token|refresh[_-]?token|client[_-]?secret|secret[_-]?access[_-]?key|private[_-]?key)\b\s*[:=]"
)
PRIVATE_KEY_MARKERS = (
    "BEGIN OPENSSH PRIVATE KEY",
    "BEGIN RSA PRIVATE KEY",
    "BEGIN EC PRIVATE KEY",
    "BEGIN PRIVATE KEY",
)


class ImportError(RuntimeError):
    pass


@dataclass(frozen=True)
class Candidate:
    source: Path
    target: Path
    size: int


def repo_root(value: str | None) -> Path:
    if value:
        return Path(value).expanduser().resolve()
    return Path(__file__).resolve().parents[1]


def imported_root(repo: Path) -> Path:
    return repo / "dotfiles/imported/fish"


def is_backupish(path: Path) -> bool:
    lowered = path.name.lower()
    if lowered in SKIP_NAMES:
        return True
    if any(part.lower() in SKIP_DIRS or part.lower().startswith("legacy-backup") for part in path.parts):
        return True
    return lowered.endswith(SKIP_SUFFIXES) or ".backup" in lowered


def inspect_file(path: Path) -> tuple[str, int]:
    try:
        size = path.stat().st_size
        raw = path.read_bytes()
    except OSError as exc:
        return f"unreadable:{exc}", 0
    if size > MAX_BYTES:
        return "too-large", size
    if b"\0" in raw:
        return "binary", size
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return "non-utf8", size
    if SENSITIVE.search(text) or any(marker in text for marker in PRIVATE_KEY_MARKERS):
        return "sensitive", size
    return "ok", size


def scan(home: Path) -> tuple[list[Candidate], list[tuple[Path, str]]]:
    root = home / ".config/fish"
    if not root.exists():
        raise ImportError(f"no existe configuración Fish: {root}")
    if root.is_symlink():
        raise ImportError(f"no se importa una raíz Fish que ya es symlink: {root}")
    if not root.is_dir():
        raise ImportError(f"la ruta Fish no es un directorio: {root}")

    accepted: list[Candidate] = []
    rejected: list[tuple[Path, str]] = []
    for path in sorted(root.rglob("*"), key=lambda item: item.as_posix()):
        rel = path.relative_to(home)
        rel_fish = path.relative_to(root)
        if is_backupish(rel_fish):
            if path.is_file() or path.is_symlink():
                rejected.append((rel, "state/backup/temp"))
            continue
        if path.is_dir():
            continue
        if path.is_symlink():
            rejected.append((rel, "symlink"))
            continue
        if not path.is_file():
            rejected.append((rel, "non-regular"))
            continue
        reason, size = inspect_file(path)
        if reason == "ok":
            accepted.append(Candidate(path, rel, size))
        else:
            rejected.append((rel, reason))

    if not accepted:
        raise ImportError("no se encontraron archivos Fish importables")
    return accepted, sorted(rejected, key=lambda item: (item[0].as_posix(), item[1]))


def render_entries(candidates: list[Candidate]) -> str:
    lines = [BEGIN, "# Generated by core/import_fish.py. Re-run the importer instead of editing this block by hand."]
    for candidate in candidates:
        target = candidate.target.as_posix()
        source = f"dotfiles/imported/fish/home/{target}"
        lines.extend([
            "",
            "[[entry]]",
            f"source = {json.dumps(source)}",
            f"target = {json.dumps(target)}",
            'tags = ["user-shell"]',
        ])
    lines.extend([END, ""])
    return "\n".join(lines)


def replace_generated_block(text: str, block: str) -> str:
    if BEGIN in text or END in text:
        if text.count(BEGIN) != 1 or text.count(END) != 1:
            raise ImportError("manifest contiene marcadores Fish inconsistentes")
        start = text.index(BEGIN)
        finish = text.index(END, start) + len(END)
        prefix = text[:start].rstrip()
        suffix = text[finish:].lstrip("\n")
        return f"{prefix}\n\n{block}{suffix}"
    return f"{text.rstrip()}\n\n{block}"


def validate_manifest(path: Path) -> None:
    with path.open("rb") as handle:
        payload = tomllib.load(handle)
    if payload.get("schema") != 1:
        raise ImportError("manifest resultante tiene schema inválido")
    targets: set[str] = set()
    for entry in payload.get("entry", []):
        target = str(entry.get("target", ""))
        if not target:
            raise ImportError("manifest resultante contiene target vacío")
        if target in targets:
            raise ImportError(f"target duplicado tras importación: {target}")
        targets.add(target)


def check_repo_paths_clean(repo: Path) -> None:
    paths = ["dotfiles/manifest.toml", "dotfiles/imported/fish"]
    proc = subprocess.run(
        ["git", "-C", str(repo), "status", "--porcelain", "--", *paths],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if proc.returncode != 0:
        raise ImportError(proc.stderr.strip() or "no se pudo consultar git status")
    if proc.stdout.strip():
        raise ImportError("el área de importación Fish ya tiene cambios locales:\n" + proc.stdout.strip())


def print_plan(home: Path, candidates: list[Candidate], rejected: list[tuple[Path, str]]) -> None:
    print(f"Cortetsu Fish import · home={home}")
    for item in candidates:
        print(f"  import       {item.target.as_posix()} ({item.size} B)")
    for target, reason in rejected:
        mark = "BLOCKED" if reason == "sensitive" else "skip"
        print(f"  {mark:12} {target.as_posix()} [{reason}]")
    print(f"SUMMARY fish={len(candidates)} skipped={len(rejected)}")


def apply(repo: Path, candidates: list[Candidate], rejected: list[tuple[Path, str]], commit: bool) -> int:
    sensitive = [target for target, reason in rejected if reason == "sensitive"]
    if sensitive:
        raise ImportError("importación bloqueada por posibles secretos: " + ", ".join(path.as_posix() for path in sensitive))

    check_repo_paths_clean(repo)
    manifest = repo / "dotfiles/manifest.toml"
    if not manifest.is_file():
        raise ImportError(f"manifest inexistente: {manifest}")
    original_manifest = manifest.read_text(encoding="utf-8")
    updated_manifest = replace_generated_block(original_manifest, render_entries(candidates))

    destination = imported_root(repo)
    destination.parent.mkdir(parents=True, exist_ok=True)
    backup = destination.with_name(f"{destination.name}.previous.{os.getpid()}")
    if backup.exists():
        shutil.rmtree(backup)

    with tempfile.TemporaryDirectory(prefix="cortetsu-fish-import-", dir=destination.parent) as tmp:
        staging = Path(tmp) / "fish"
        stage_home = staging / "home"
        stage_home.mkdir(parents=True)
        for candidate in candidates:
            out = stage_home / candidate.target
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(candidate.source, out)

        manifest_tmp = manifest.with_name(f"{manifest.name}.tmp.{os.getpid()}")
        manifest_tmp.write_text(updated_manifest, encoding="utf-8")
        validate_manifest(manifest_tmp)
        try:
            if destination.exists():
                destination.rename(backup)
            staging.rename(destination)
            os.replace(manifest_tmp, manifest)
        except Exception:
            manifest_tmp.unlink(missing_ok=True)
            manifest.write_text(original_manifest, encoding="utf-8")
            if destination.exists():
                shutil.rmtree(destination)
            if backup.exists():
                backup.rename(destination)
            raise
        else:
            shutil.rmtree(backup, ignore_errors=True)

    print(f"IMPORTED fish={destination}")
    print(f"MANIFEST entries={len(candidates)}")
    if rejected:
        print(f"SKIPPED count={len(rejected)}")

    if commit:
        subprocess.run(
            ["git", "-C", str(repo), "add", "--", "dotfiles/manifest.toml", "dotfiles/imported/fish"],
            check=True,
        )
        diff = subprocess.run(["git", "-C", str(repo), "diff", "--cached", "--quiet"]).returncode
        if diff == 0:
            print("COMMIT skipped=no changes")
        else:
            host = socket.gethostname().split(".")[0]
            stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            subprocess.run(
                ["git", "-C", str(repo), "commit", "-m", f"feat(dotfiles): import Fish config from {host} ({stamp})"],
                check=True,
            )
            print("COMMIT created=Fish import")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Safely import ~/.config/fish into Cortetsu")
    parser.add_argument("action", choices=("plan", "apply"), nargs="?", default="plan")
    parser.add_argument("--repo")
    parser.add_argument("--home", type=Path, default=Path.home())
    parser.add_argument("--commit", action="store_true", help="stage only Fish import files and create a local commit")
    args = parser.parse_args()

    repo = repo_root(args.repo)
    home = args.home.expanduser().resolve()
    try:
        candidates, rejected = scan(home)
        print_plan(home, candidates, rejected)
        if args.action == "apply":
            return apply(repo, candidates, rejected, args.commit)
        return 0
    except ImportError as exc:
        print(f"ERROR: {exc}", file=os.sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
