// Generated by core/theme.py from ~/.config/cortetsu/ui.toml source.
// Do not hand-edit; run `cortetsu theme compile`.
.pragma library

var colorSumi = "#0B0D10"
var colorTetsu = "#171B21"
var colorWashi = "#E7E0D5"
var colorIndigo = "#334E68"
var colorVermillion = "#D64B32"
var colorMuted = "#8A919B"

var radiusSmall = 8
var radiusMedium = 14
var radiusLarge = 22

var spacingUnit = 4
var spacingCompact = 8
var spacingStandard = 12
var spacingComfortable = 20
var spacingSpacious = 28

var hoverScale = 1.04
var motionInstantMs = 70
var motionFastMs = 100
var motionStandardMs = 160
var motionDeliberateMs = 220
